In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 

import joblib 
import warnings

warnings.filterwarnings('ignore')

from datasets import load_dataset

In [2]:
headphone = pd.read_csv('../datasets/Headphones.csv')
all_electronics = pd.read_csv("../datasets/All Electronics.csv")
all_appliances = pd.read_csv("../datasets/All Appliances.csv")
car_accessories = pd.read_csv("../datasets/Car Accessories.csv")

In [3]:
headphone.shape

(9600, 9)

In [4]:
all_electronics.shape

(9600, 9)

In [5]:
all_appliances.shape

(9576, 9)

In [6]:
car_accessories.shape

(1392, 9)

In [7]:
all_appliances.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Pigeon by Stovekraft Amaze Plus Electric Kettl...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Amaze-Plus-1-5-Lt...,3.9,"128,941",₹599,"₹1,245"
1,Pigeon Polypropylene Mini Handy and Compact Ch...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Pigeon-Stovekraft-Plasti...,4.1,"274,505",₹199,₹545
2,Glun Multipurpose Portable Electronic Digital ...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Multipurpose-Portable-El...,3.8,365,₹199,₹899
3,beatXP Kitchen Scale Multipurpose Portable Ele...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/beatXP-Multipurpose-Port...,3.7,"3,290",₹299,"₹1,999"
4,Bajaj DX-6 1000W Dry Iron with Advance Solepla...,appliances,All Appliances,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Bajaj-Majesty-1000-Watt-...,4.2,"24,380",₹625,"₹1,400"

In [8]:
df = pd.concat(
    [headphone ,
    all_appliances ,
    all_electronics ,
    car_accessories ],
    ignore_index=True
)

In [9]:
df = df.sample(frac=1 , random_state=42).reset_index(drop=True)

In [10]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51HFlB4cO9...,https://www.amazon.in/TheGiftKart-Ultra-Hybrid...,4.8,64,₹379,₹999
1,Wireless Bluetooth Headphones Earphone For Nok...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/I/51DnK-uBB3...,https://www.amazon.in/Nokia-Lumia-900-Sweat-Re...,NaN,NaN,₹899,"₹1,499"
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/GIZGA-inch-Hard-Drive-Bl...,4.5,"14,161",₹199,₹599
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Rich-Care-Earphone-Hands...,3.5,39,₹499,₹699
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,https://m.media-amazon.com/images/I/51UuhcQ45p...,https://www.amazon.in/Planet-Noah-Enviropure-E...,3.2,21,₹349.10,"₹1,999"

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30168 entries, 0 to 30167
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            30168 non-null  object
 1   main_category   30168 non-null  object
 2   sub_category    30168 non-null  object
 3   image           30168 non-null  object
 4   link            30168 non-null  object
 5   ratings         26791 non-null  object
 6   no_of_ratings   26791 non-null  object
 7   discount_price  28673 non-null  object
 8   actual_price    29678 non-null  object
dtypes: object(9)
memory usage: 2.1+ MB

In [12]:
df.isnull().sum()

name                 0
main_category        0
sub_category         0
image                0
link                 0
ratings           3377
no_of_ratings     3377
discount_price    1495
actual_price       490
dtype: int64

In [13]:
df['sub_category'].value_counts()

sub_category
All Electronics    9600
Headphones         9600
All Appliances     9576
Car Accessories    1392
Name: count, dtype: int64

In [14]:
df['ratings']=df['ratings'].fillna(0)

In [15]:
df['no_of_ratings'] = df['no_of_ratings'].fillna(0)

In [16]:
df['discount_price'] = df['discount_price'].fillna(df['actual_price'])

In [17]:
df.dropna(inplace=True)

In [18]:
df.isnull().sum()

name              0
main_category     0
sub_category      0
image             0
link              0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64

In [19]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51HFlB4cO9...,https://www.amazon.in/TheGiftKart-Ultra-Hybrid...,4.8,64,₹379,₹999
1,Wireless Bluetooth Headphones Earphone For Nok...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/I/51DnK-uBB3...,https://www.amazon.in/Nokia-Lumia-900-Sweat-Re...,0,0,₹899,"₹1,499"
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/GIZGA-inch-Hard-Drive-Bl...,4.5,"14,161",₹199,₹599
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Rich-Care-Earphone-Hands...,3.5,39,₹499,₹699
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,https://m.media-amazon.com/images/I/51UuhcQ45p...,https://www.amazon.in/Planet-Noah-Enviropure-E...,3.2,21,₹349.10,"₹1,999"

In [20]:
# df['discount_price'] = df['discount_price'].split('₹')[1]
df['discount_price'] = df['discount_price'].apply(lambda x : x.split('₹')[1])
df['actual_price'] = df['actual_price'].apply(lambda x : x.split('₹')[1])

In [21]:
df['discount_price'] = df['discount_price'].str.replace(',' , '').astype('float')
df['actual_price'] = df['actual_price'].str.replace(',' , '').astype('float')

In [22]:
df1 = df.copy()

In [23]:
df['no_of_ratings'].unique()

array(['64', 0, '14,161', ..., '4,567', '4,283', '5,150'],
      shape=(4496,), dtype=object)

In [24]:
df['no_of_ratings'] = pd.to_numeric(
    df['no_of_ratings']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+)')[0],
    errors='coerce'
)

df['ratings'] = pd.to_numeric(
    df['ratings']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+)')[0],
    errors='coerce'
)

In [25]:
df[['no_of_ratings' , 'ratings']] = df[['no_of_ratings' , 'ratings']].fillna(0)

In [26]:
df['no_of_ratings'] = df['no_of_ratings'].astype('int')

In [27]:
df['ratings'] = df['ratings'].astype('float')

In [28]:
df.head(2)

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51HFlB4cO9...,https://www.amazon.in/TheGiftKart-Ultra-Hybrid...,4.0,64,379.0,999.0
1,Wireless Bluetooth Headphones Earphone For Nok...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/I/51DnK-uBB3...,https://www.amazon.in/Nokia-Lumia-900-Sweat-Re...,0.0,0,899.0,1499.0

In [29]:
df['name'].nunique()

26147

In [30]:
df = df.drop_duplicates(subset='name')

In [31]:
df['name'].value_counts().head(20)

name
TheGiftKart Ultra-Hybrid Crystal Clear Back Case Cover for Samsung Galaxy S23 Ultra 5G | Shockproof Design | Camera Protec...    1
Spigen EZ Fit Tempered Glass Screen Protector for iPhone 14 Plus / 13 Pro Max - 2 Pack (Sensor Protection)                       1
New Ware® 5 Meter Multipurpose Hose Pipe for AC Outlet Drain Water                                                               1
Spigen Liquid Air Back Cover Case Compatible for Google Pixel 7 (TPU | Matte Black)                                              1
HoneyTail Multipurpose Roti Maker Electric Automatic, chapati Maker Electric Automatic, roti Maker Machine with 1000 Watts...    1
Saco Silicone Skin Keyboard Cover Compatible for HP Pavilion Power 15-cb518TX 15.6-inch Full HD Gaming Laptop - Black            1
World Of PLAY, Play WE25 Wired Earphone, Headsets with Mic & 14.2 mm EBEL Drivers with Heavy Bass Audio - Black                  1
SYGA Professional Sketch and Drawing Pencils ，Art Pencil Box Contains 12 Pieces Set B 2B 3B 4B 5B 6B 7B 8B HB H 2H F             1
BONIFA Megnet Wireless Bluetooth Headphones, Headset with Mic and Sound Button Earphone for Note 5/6/7 Pro, 6A, Y2, A2, A...     1
Street27 100 Pieces/Pack White Washable Iron on Name Labels Garment Fabric Tags Marker Set for School Clothes Sewing Acces...    1
AUTOFACT Magnetic Window Sunshade for Tata Nexon -Set of 4 - with Zipper                                                         1
Makarana Marble Chakla & Belan/ Roti Maker                                                                                       1
Portronics Ruffpad 8.5M Multicolor LCD Writing Pad with Screen 21.5cm (8.5-inch) for Drawing, Playing, Handwriting Gifts f...    1
Bajaj New Bahar Deco 1200mm Ceiling Fan (Brown)                                                                                  1
SanDisk Ultra microSD UHS-I Card 128GB, 120MB/s R                                                                                1
iNNOVATiON ENTERPRiSES Part Code (31141596DG01145) Utility Shelf for Middle Door Compatible for GODREJ Edge GDE19CS4 ONLY        1
Affix Auto-Align Technology Tempered Glass Screen Guard for iPhone 14, iPhone 13 and for iPhone 13 Pro (6.1 Inch) | Easy I...    1
Lauret Blanc Notebook - A5 Size, 144 Ruled Pages Diary Journal, 80 GSM Natural Shade. (Style 6)                                  1
Wireless Bluetooth Headphones Earphone For Xiaomi Mi A2 Lite (Redmi 6 Pro) Neckband Earphone Bluetooth 5.0 Wireless Headph...    1
Amazpro Combo Pack of 2 Items - Comfortable On-Ear Bluetooth Wireless Headphone, Comfortable On-Ear Bluetooth Wireless Hea...    1
Name: count, dtype: int64

In [32]:
df.shape

(26147, 9)

In [33]:
df['product Id'] = 'P' + (df.index + 1).astype('str')

In [34]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,product Id
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51HFlB4cO9...,https://www.amazon.in/TheGiftKart-Ultra-Hybrid...,4.0,64,379.0,999.0,P1
1,Wireless Bluetooth Headphones Earphone For Nok...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/I/51DnK-uBB3...,https://www.amazon.in/Nokia-Lumia-900-Sweat-Re...,0.0,0,899.0,1499.0,P2
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/GIZGA-inch-Hard-Drive-Bl...,4.0,14161,199.0,599.0,P3
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,"tv, audio & cameras",Headphones,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Rich-Care-Earphone-Hands...,3.0,39,499.0,699.0,P4
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,https://m.media-amazon.com/images/I/51UuhcQ45p...,https://www.amazon.in/Planet-Noah-Enviropure-E...,3.0,21,349.1,1999.0,P5

In [35]:
metadata = df[['product Id' , 'image' , 'link']]
df.drop(columns=['image' , 'link'] , axis=1 , inplace=True)

In [36]:
metadata['name'] = df['name']

In [37]:
metadata.head()

,product Id,image,link,name
0,P1,https://m.media-amazon.com/images/I/51HFlB4cO9...,https://www.amazon.in/TheGiftKart-Ultra-Hybrid...,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...
1,P2,https://m.media-amazon.com/images/I/51DnK-uBB3...,https://www.amazon.in/Nokia-Lumia-900-Sweat-Re...,Wireless Bluetooth Headphones Earphone For Nok...
2,P3,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/GIZGA-inch-Hard-Drive-Bl...,"Gizga Essentials Hard Drive Case Shell, 6.35cm..."
3,P4,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Rich-Care-Earphone-Hands...,Rich Care Great Sound of Bass Wired in-Ear Ear...
4,P5,https://m.media-amazon.com/images/I/51UuhcQ45p...,https://www.amazon.in/Planet-Noah-Enviropure-E...,Planet Noah Maxx Enviropure Power Saver & Mone...

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26147 entries, 0 to 30167
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            26147 non-null  object
 1   main_category   26147 non-null  object
 2   sub_category    26147 non-null  object
 3   ratings         26147 non-null  float64
 4   no_of_ratings   26147 non-null  int64
 5   discount_price  26147 non-null  float64
 6   actual_price    26147 non-null  float64
 7   product Id      26147 non-null  object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.8+ MB

In [41]:
df['discount percentage'] = (((df['actual_price'] - df['discount_price']) / df['actual_price']) * 100).fillna(0)

In [48]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,"tv, audio & cameras",All Electronics,4.0,64,379.0,999.0,P1,62.062062,Good
1,Wireless Bluetooth Headphones Earphone For Nok...,"tv, audio & cameras",Headphones,0.0,0,899.0,1499.0,P2,40.026684,Unrated
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...","tv, audio & cameras",All Electronics,4.0,14161,199.0,599.0,P3,66.777963,Good
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,"tv, audio & cameras",Headphones,3.0,39,499.0,699.0,P4,28.612303,Average
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,3.0,21,349.1,1999.0,P5,82.536268,Average

In [44]:
df['ratings'].value_counts()

ratings
4.0    11432
3.0     9018
0.0     3243
2.0     1048
5.0      938
1.0      468
Name: count, dtype: int64

In [47]:
df['Rating Bucket'] = np.where(
    df['ratings'] == 0,
    'Unrated',
    pd.cut(
        df['ratings'],
        bins=[0, 2, 3, 4, 5],
        labels=['Low', 'Average', 'Good', 'Excellent']
    )
)

In [49]:
df['Popularity Score'] = (
    df['ratings'] * np.log1p(df['no_of_ratings'])
)

In [51]:
df['Value Score'] = (
    df['Popularity Score'] / df['discount_price']
).fillna(0.0)

In [54]:
noise_words = [
    "premium",
    "original",
    "latest",
    "best",
    "new",
    "quality"
]

def clean_text(name):
    name = name.lower()
    for word in noise_words:
        name = name.replace(word , "")

    return name
df['cleaned_name'] = df['name'].apply(lambda name : clean_text(name))

In [62]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket,Popularity Score,Value Score,cleaned_name
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,tv audio camera,All Electronics,4.0,64,379.0,999.0,P1,62.062062,Good,16.697549,0.044057,thegiftkart ultra-hybrid crystal clear back ca...
1,Wireless Bluetooth Headphones Earphone For Nok...,tv audio camera,Headphones,0.0,0,899.0,1499.0,P2,40.026684,Unrated,0.000000,0.000000,wireless bluetooth headphones earphone for nok...
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...",tv audio camera,All Electronics,4.0,14161,199.0,599.0,P3,66.777963,Good,38.233270,0.192127,"gizga essentials hard drive case shell, 6.35cm..."
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,tv audio camera,Headphones,3.0,39,499.0,699.0,P4,28.612303,Average,11.066638,0.022178,rich care great sound of bass wired in-ear ear...
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,3.0,21,349.1,1999.0,P5,82.536268,Average,9.273127,0.026563,planet noah maxx enviropure power saver & mone...

In [60]:
df['sub_category'].unique()

array(['All Electronics', 'Headphones', 'All Appliances',
       'Car Accessories'], dtype=object)

In [61]:
df['main_category'] = df['main_category'].str.replace("tv, audio & cameras" , "tv audio camera")

In [65]:
df['cleaned_sub_category'] = (
    df['sub_category']
    .str.replace("All Electronics", "Electronics", regex=False)
    .str.replace("All Appliances", "Appliances", regex=False)
)

In [68]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket,Popularity Score,Value Score,cleaned_name,cleaned_sub_category
0,TheGiftKart Ultra-Hybrid Crystal Clear Back Ca...,tv audio camera,All Electronics,4.0,64,379.0,999.0,P1,62.062062,Good,16.697549,0.044057,thegiftkart ultrahybrid crystal clear back cas...,Electronics
1,Wireless Bluetooth Headphones Earphone For Nok...,tv audio camera,Headphones,0.0,0,899.0,1499.0,P2,40.026684,Unrated,0.000000,0.000000,wireless bluetooth headphones earphone for nok...,Headphones
2,"Gizga Essentials Hard Drive Case Shell, 6.35cm...",tv audio camera,All Electronics,4.0,14161,199.0,599.0,P3,66.777963,Good,38.233270,0.192127,"gizga essentials hard drive case shell, 635cm2...",Electronics
3,Rich Care Great Sound of Bass Wired in-Ear Ear...,tv audio camera,Headphones,3.0,39,499.0,699.0,P4,28.612303,Average,11.066638,0.022178,rich care great sound of bass wired inear earp...,Headphones
4,Planet Noah Maxx Enviropure Power Saver & Mone...,appliances,All Appliances,3.0,21,349.1,1999.0,P5,82.536268,Average,9.273127,0.026563,planet noah maxx enviropure power saver & mone...,Appliances

In [67]:
df['cleaned_name'] = (
    df['cleaned_name']
    .str.replace('...','')
    .str.replace('..','')
    .str.replace('.','')
    .str.replace('-','')
    .str.replace('|','')
    .str.replace('||','')
    .str.replace('/','')
    .str.replace('+','')   
)

In [72]:
df['tags'] = (df['main_category'] + " "  + df['sub_category'] + " " + df['name'])

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26147 entries, 0 to 30167
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  26147 non-null  object
 1   main_category         26147 non-null  object
 2   sub_category          26147 non-null  object
 3   ratings               26147 non-null  float64
 4   no_of_ratings         26147 non-null  int64
 5   discount_price        26147 non-null  float64
 6   actual_price          26147 non-null  float64
 7   product Id            26147 non-null  object
 8   discount percentage   26147 non-null  float64
 9   Rating Bucket         26147 non-null  object
 10  Popularity Score      26147 non-null  float64
 11  Value Score           26147 non-null  float64
 12  cleaned_name          26147 non-null  object
 13  cleaned_sub_category  26147 non-null  object
 14  tags                  26147 non-null  object
dtypes: float64(6), int64(1), object(8)
memory usage: 3.2+ MB

In [75]:
df.to_csv("../cleaned Datasets/ProductInfo.csv" , index=False)
metadata.to_csv("../cleaned Datasets/MetaData.csv" , index=False)