In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 

import joblib 
import warnings

warnings.filterwarnings('ignore')

from datasets import load_dataset

In [2]:
headphone = pd.read_csv('../datasets/Headphones.csv')
all_electronics = pd.read_csv("../datasets/All Electronics.csv")
all_appliances = pd.read_csv("../datasets/All Appliances.csv")
car_accessories = pd.read_csv("../datasets/Car Accessories.csv")
Ethnic_wear = pd.read_csv("../datasets/Ethnic Wear.csv")
HomeDecor = pd.read_csv("../datasets/Home Dcor.csv")
HomeEntertainment = pd.read_csv("../datasets/Home Entertainment Systems.csv")
MensFashion = pd.read_csv("../datasets/Mens Fashion.csv")

In [3]:
data = [headphone , all_electronics , all_appliances , car_accessories , Ethnic_wear , HomeDecor , HomeEntertainment , MensFashion]

for datamodel in data:
    print(f"{datamodel.shape}")

(9600, 9)
(9600, 9)
(9576, 9)
(1392, 9)
(19056, 9)
(1272, 9)
(9576, 9)
(19200, 9)

In [4]:
df = pd.concat(
    data , 
    ignore_index=True
)

In [5]:
df = df.sample(frac=1 , random_state=42).reset_index(drop=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79272 entries, 0 to 79271
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            79272 non-null  object
 1   main_category   79272 non-null  object
 2   sub_category    79272 non-null  object
 3   image           79272 non-null  object
 4   link            79272 non-null  object
 5   ratings         69656 non-null  object
 6   no_of_ratings   69656 non-null  object
 7   discount_price  74694 non-null  object
 8   actual_price    78254 non-null  object
dtypes: object(9)
memory usage: 5.4+ MB

In [7]:
df.isnull().sum()

name                 0
main_category        0
sub_category         0
image                0
link                 0
ratings           9616
no_of_ratings     9616
discount_price    4578
actual_price      1018
dtype: int64

In [8]:
print(df['sub_category'].value_counts())
print()
print(df['main_category'].value_counts())

sub_category
Men's Fashion                 19200
Ethnic Wear                   19056
All Electronics                9600
Headphones                     9600
All Appliances                 9576
Home Entertainment Systems     9576
Car Accessories                1392
Home Décor                     1272
Name: count, dtype: int64

main_category
tv, audio & cameras    28776
stores                 19200
women's clothing       19056
appliances              9576
car & motorbike         1392
home & kitchen          1272
Name: count, dtype: int64

In [9]:
df['ratings']=df['ratings'].fillna(0)

In [10]:
df['no_of_ratings'] = df['no_of_ratings'].fillna(0)

In [11]:
df['discount_price'] = df['discount_price'].fillna(df['actual_price'])

In [12]:
df.isnull().sum()

name                 0
main_category        0
sub_category         0
image                0
link                 0
ratings              0
no_of_ratings        0
discount_price    1018
actual_price      1018
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.isnull().sum()

name              0
main_category     0
sub_category      0
image             0
link              0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64

In [15]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,https://m.media-amazon.com/images/I/21h-aU43wL...,https://www.amazon.in/Gadson-Solenoid-Valve-Aq...,3.7,292,₹150,₹300
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,https://m.media-amazon.com/images/I/91RVshFBEM...,https://www.amazon.in/Van-Heusen-Sport-Shirt-V...,4.2,5,₹619,"₹2,299"
2,Generic 1 PC LCD Digital Kitchen Measuring Spo...,appliances,All Appliances,https://m.media-amazon.com/images/I/41Wo+gg3Jh...,https://www.amazon.in/Generic-Digital-Kitchen-...,0,0,₹799,"₹3,054"
3,"JBL Endurance Run 2, Sports in Ear Wired Earph...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61cWki-Zt1...,https://www.amazon.in/JBL-Endurance-Earphones-...,4.2,"25,356","₹1,199","₹1,799"
4,CevPure CSM 80 GPD Original RO Membrane with F...,appliances,All Appliances,https://m.media-amazon.com/images/I/41JTLo5zdG...,https://www.amazon.in/Original-Membrane-Restri...,5.0,2,₹799,"₹1,999"

In [16]:
# df['discount_price'] = df['discount_price'].split('₹')[1]
df['discount_price'] = df['discount_price'].apply(lambda x : x.split('₹')[1])
df['actual_price'] = df['actual_price'].apply(lambda x : x.split('₹')[1])

In [17]:
df['discount_price'] = df['discount_price'].str.replace(',' , '').astype('float')
df['actual_price'] = df['actual_price'].str.replace(',' , '').astype('float')

In [18]:
df['no_of_ratings'] = pd.to_numeric(
    df['no_of_ratings']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+)')[0],
    errors='coerce'
)

df['ratings'] = pd.to_numeric(
    df['ratings']
        .astype(str)
        .str.replace(',', '', regex=False)
        .str.extract(r'(\d+)')[0],
    errors='coerce'
)

In [19]:
df[['no_of_ratings' , 'ratings']] = df[['no_of_ratings' , 'ratings']].fillna(0)

In [20]:
df['no_of_ratings'] = df['no_of_ratings'].astype('int')

In [21]:
df['ratings'] = df['ratings'].astype('float')

In [22]:
df.head(2)

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,https://m.media-amazon.com/images/I/21h-aU43wL...,https://www.amazon.in/Gadson-Solenoid-Valve-Aq...,3.0,292,150.0,300.0
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,https://m.media-amazon.com/images/I/91RVshFBEM...,https://www.amazon.in/Van-Heusen-Sport-Shirt-V...,4.0,5,619.0,2299.0

In [23]:
df['name'].nunique()

66960

In [24]:
df = df.drop_duplicates(subset='name')

In [25]:
df['name'].value_counts().head(20)

name
Gadson RO Solenoid Valve 24 VDC for Kent/AQUAGARD RO Water Purifier GV507                                                        1
La Festiya Women's Floral Net Dupatta (LF-Dupatta_Red_2.25M by 1M)                                                               1
Jaipur Kurti Women's Cotton Straight Salwar Suit Set                                                                             1
Arrow Men Polo Shirt                                                                                                             1
Elleven Women Palazzo                                                                                                            1
ANiQA Wired In Ear Earphone with Mic (Black)                                                                                     1
VJ Fashion Side Rope Saree Shapewear, Skirts for Women, Petticoat, Cotton Blended Shape Wear for Saree                           1
kainoz Crystal Pipe Latkan for Lehenga Blouse Saree & Duppatta                                                                   1
Lasafiya Women's Western Fit Printed Palazzo Pant for Women & Girls (Free Size) (26 to 40)                                       1
KDM K215 Stereo Wired Earphone with Mic (Black)                                                                                  1
INALSA Dura Clean Plus Upright Vacuum Cleaner, 2-in-1,Handheld & Stick for Home & Office Use,800W- with 16KPA Strong Sucti...    1
TIMEX Slim Sapphire Crystal Analog Grey Dial Men's Watch-TWEG17413                                                               1
Titan Gents Karishma Analog Brown Dial Men's Watch-NN1824KM01                                                                    1
W for Woman Women's Cotton Blend Kurta, Tight & Dupatta (22FEWS17460-312187_Ecru                                                 1
PTron Boom Ultima V2 Dual Driver, in Ear Gaming Wired Earphones with Mic, Volume Control, Passive Noise Cancelling Boom 3 ...    1
Rajnandini Women's Cotton Silk Woven Check Print Traditional Saree With Blouse Piece                                             1
Small Sewing Machine For Home Non Electric Mini Hand Stitching Silai Kit Stapler Manual Sewing Machine (Built-in Stitches 2)     1
Briqre Victory Nutri Blender Complete Kitchen Machine, Mixer Grinder, Blender, Chopper, Juicer, Stainless Steel Blades, 2 ...    1
Amazon Basics Bluetooth 5.0 Truly Wireless in Ear Earbuds with mic, Up to 38 Hours Playtime, IPX-5 Rated, Type-C Charging ...    1
Vaamsi Women's A-Line Kurta                                                                                                      1
Name: count, dtype: int64

In [26]:
df.shape

(66960, 9)

In [27]:
df['product Id'] = 'P' + (df.index + 1).astype('str')

In [28]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,product Id
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,https://m.media-amazon.com/images/I/21h-aU43wL...,https://www.amazon.in/Gadson-Solenoid-Valve-Aq...,3.0,292,150.0,300.0,P1
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,https://m.media-amazon.com/images/I/91RVshFBEM...,https://www.amazon.in/Van-Heusen-Sport-Shirt-V...,4.0,5,619.0,2299.0,P2
2,Generic 1 PC LCD Digital Kitchen Measuring Spo...,appliances,All Appliances,https://m.media-amazon.com/images/I/41Wo+gg3Jh...,https://www.amazon.in/Generic-Digital-Kitchen-...,0.0,0,799.0,3054.0,P3
3,"JBL Endurance Run 2, Sports in Ear Wired Earph...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61cWki-Zt1...,https://www.amazon.in/JBL-Endurance-Earphones-...,4.0,25356,1199.0,1799.0,P4
4,CevPure CSM 80 GPD Original RO Membrane with F...,appliances,All Appliances,https://m.media-amazon.com/images/I/41JTLo5zdG...,https://www.amazon.in/Original-Membrane-Restri...,5.0,2,799.0,1999.0,P5

In [29]:
metadata = df[['product Id' ,'name' ,'sub_category' ,  'main_category' , 'image' , 'link' , 'discount_price' , 'actual_price' , 'ratings' , 'no_of_ratings']]
df.drop(columns=['image' , 'link'] , axis=1 , inplace=True)

In [30]:
metadata.head()

,product Id,name,sub_category,main_category,image,link,discount_price,actual_price,ratings,no_of_ratings
0,P1,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,All Appliances,appliances,https://m.media-amazon.com/images/I/21h-aU43wL...,https://www.amazon.in/Gadson-Solenoid-Valve-Aq...,150.0,300.0,3.0,292
1,P2,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,Men's Fashion,stores,https://m.media-amazon.com/images/I/91RVshFBEM...,https://www.amazon.in/Van-Heusen-Sport-Shirt-V...,619.0,2299.0,4.0,5
2,P3,Generic 1 PC LCD Digital Kitchen Measuring Spo...,All Appliances,appliances,https://m.media-amazon.com/images/I/41Wo+gg3Jh...,https://www.amazon.in/Generic-Digital-Kitchen-...,799.0,3054.0,0.0,0
3,P4,"JBL Endurance Run 2, Sports in Ear Wired Earph...",All Electronics,"tv, audio & cameras",https://m.media-amazon.com/images/I/61cWki-Zt1...,https://www.amazon.in/JBL-Endurance-Earphones-...,1199.0,1799.0,4.0,25356
4,P5,CevPure CSM 80 GPD Original RO Membrane with F...,All Appliances,appliances,https://m.media-amazon.com/images/I/41JTLo5zdG...,https://www.amazon.in/Original-Membrane-Restri...,799.0,1999.0,5.0,2

In [31]:
df['discount percentage'] = (((df['actual_price'] - df['discount_price']) / df['actual_price']) * 100).fillna(0)

In [32]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,3.0,292,150.0,300.0,P1,50.000000
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,4.0,5,619.0,2299.0,P2,73.075250
2,Generic 1 PC LCD Digital Kitchen Measuring Spo...,appliances,All Appliances,0.0,0,799.0,3054.0,P3,73.837590
3,"JBL Endurance Run 2, Sports in Ear Wired Earph...","tv, audio & cameras",All Electronics,4.0,25356,1199.0,1799.0,P4,33.351862
4,CevPure CSM 80 GPD Original RO Membrane with F...,appliances,All Appliances,5.0,2,799.0,1999.0,P5,60.030015

In [33]:
df['ratings'].value_counts()

ratings
3.0    26728
4.0    24414
0.0     8789
5.0     3313
2.0     2705
1.0     1011
Name: count, dtype: int64

In [34]:
df['Rating Bucket'] = np.where(
    df['ratings'] == 0,
    'Unrated',
    pd.cut(
        df['ratings'],
        bins=[0, 2, 3, 4, 5],
        labels=['Low', 'Average', 'Good', 'Excellent']
    )
)

In [35]:
df['Popularity Score'] = (
    df['ratings'] * np.log1p(df['no_of_ratings'])
)

In [36]:
df['Value Score'] = (
    df['Popularity Score'] / df['discount_price']
).fillna(0.0)

In [37]:
noise_words = [
    "premium",
    "original",
    "latest",
    "best",
    "new",
    "quality"
]

def clean_text(name):
    name = name.lower()
    for word in noise_words:
        name = name.replace(word , "")

    return name
df['cleaned_name'] = df['name'].apply(lambda name : clean_text(name))

In [38]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket,Popularity Score,Value Score,cleaned_name
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,3.0,292,150.0,300.0,P1,50.000000,Average,17.040518,0.113603,gadson ro solenoid valve 24 vdc for kent/aquag...
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,4.0,5,619.0,2299.0,P2,73.075250,Good,7.167038,0.011578,van heusen sport men's slim shirt (vssfwslp299...
2,Generic 1 PC LCD Digital Kitchen Measuring Spo...,appliances,All Appliances,0.0,0,799.0,3054.0,P3,73.837590,Unrated,0.000000,0.000000,generic 1 pc lcd digital kitchen measuring spo...
3,"JBL Endurance Run 2, Sports in Ear Wired Earph...","tv, audio & cameras",All Electronics,4.0,25356,1199.0,1799.0,P4,33.351862,Good,40.563240,0.033831,"jbl endurance run 2, sports in ear wired earph..."
4,CevPure CSM 80 GPD Original RO Membrane with F...,appliances,All Appliances,5.0,2,799.0,1999.0,P5,60.030015,Excellent,5.493061,0.006875,cevpure csm 80 gpd ro membrane with flow rest...

In [40]:
df['sub_category'].unique()

array(['All Appliances', "Men's Fashion", 'All Electronics',
       'Ethnic Wear', 'Home Entertainment Systems', 'Headphones',
       'Home Décor', 'Car Accessories'], dtype=object)

In [39]:
df['main_category'].value_counts()

main_category
tv, audio & cameras    24421
women's clothing       16183
stores                 15267
appliances              8503
car & motorbike         1381
home & kitchen          1205
Name: count, dtype: int64

In [41]:
df['main_category'] = df['main_category'].str.replace("tv, audio & cameras" , "tv audio camera")
df['main_category'] = df['main_category'].str.replace("women's clothing" , "women clothing")
df['main_category'] = df['main_category'].str.replace("car & motorbike" , "car motorbike")
df['main_category'] = df['main_category'].str.replace("home & kitchen" , "home kitchen")

In [42]:
df['sub_category'].value_counts()

sub_category
Ethnic Wear                   16183
Men's Fashion                 15267
All Appliances                 8503
Home Entertainment Systems     8503
All Electronics                8076
Headphones                     7842
Car Accessories                1381
Home Décor                     1205
Name: count, dtype: int64

In [43]:
df['cleaned_sub_category'] = (
    df['sub_category']
    .str.replace("All Electronics", "Electronics", regex=False)
    .str.replace("All Appliances", "Appliances", regex=False)
    .str.replace("Men Fashion", "Men Fashion", regex=False)
)

In [58]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,product Id,discount percentage,Rating Bucket,Popularity Score,Value Score,cleaned_name,cleaned_sub_category
0,Gadson RO Solenoid Valve 24 VDC for Kent/AQUAG...,appliances,All Appliances,3.0,292,150.0,300.0,P1,50.000000,Average,17.040518,0.113603,gadson ro solenoid valve 24 vdc for kent/aquag...,Appliances
1,Van Heusen Sport Men's Slim Shirt (VSSFWSLP299...,stores,Men's Fashion,4.0,5,619.0,2299.0,P2,73.075250,Good,7.167038,0.011578,van heusen sport men's slim shirt (vssfwslp299...,Men's Fashion
2,Generic 1 PC LCD Digital Kitchen Measuring Spo...,appliances,All Appliances,0.0,0,799.0,3054.0,P3,73.837590,Unrated,0.000000,0.000000,generic 1 pc lcd digital kitchen measuring spo...,Appliances
3,"JBL Endurance Run 2, Sports in Ear Wired Earph...",tv audio camera,All Electronics,4.0,25356,1199.0,1799.0,P4,33.351862,Good,40.563240,0.033831,"jbl endurance run 2, sports in ear wired earph...",Electronics
4,CevPure CSM 80 GPD Original RO Membrane with F...,appliances,All Appliances,5.0,2,799.0,1999.0,P5,60.030015,Excellent,5.493061,0.006875,cevpure csm 80 gpd ro membrane with flow rest...,Appliances

In [44]:
df['cleaned_name'] = (
    df['cleaned_name']
    .str.replace('...','')
    .str.replace('..','')
    .str.replace('.','')
    .str.replace('-','')
    .str.replace('|','')
    .str.replace('||','')
    .str.replace('/','')
    .str.replace('+','')   
)

In [45]:
df['tags'] = (df['main_category'] + " "  + df['sub_category'] + " " + df['name'])

In [46]:
df.to_csv("../cleaned Datasets/ProductInfo.csv" , index=False)
metadata.to_csv("../cleaned Datasets/MetaData.csv" , index=False)